public class TriggerHandlerAccountContact {
	// Static variable value will not change during entire process.
	// Update Contact Description 
   /* public static void Method1(Map<Id,Account> mapAccount,List<Contact> listcon){
        List<Contact> listContact = new List<Contact>();
       
        if(listcon.size()>0){
            for(Contact con : listcon){
                con.Description = mapAccount.get(con.AccountId).Industry;
                listContact.add(con);
            }
            update listcontact;
        }
    }
// -------------------***********************************-------------------------------------------------------
    // Update firstname of contact whenever Account is updated. 
    
    public static void Method2(Map<Id,Account> accMap,List<Contact> ltCon){
        List<Contact> listUpdate = new List<Contact>();
        if(ltcon.size()>0){
            for(Contact c : ltcon){
                c.FirstName = accMap.get(c.AccountId).Name;
                listupdate.add(c);
            }
            update listupdate;
        }
    }*/
}